swagger: "2.0"

info:
  version: "1.0"
  title: Open Weather API
  description: |
              Get current weather for any cities in the world.
              Get your account and all information from https://openweathermap.org
  contact:
    name: Exosite
    email: support@exosite.com

host: api.openweathermap.org
basePath: "/data/2.5"
x-exosite-health-path: "/"
x-exosite-config-parameters:
  - name: appid
    title: API Key
    description: The API Key, provided from the OpenWeatherMap account
    type: string
    required: true
  - name: lang
    title: Language
    description: Default language
    type: string
    default: en
    pattern: "[a-zA-Z]+(_[a-zA-Z]+)?"
  - name: units
    title: Units
    description: Default units type to return
    type: string
    default: metric
    enum:
      - imperial
      - metric

parameters:
  Appid:
    name: appid
    in: query
    description: Application token
    type: string
    required: true
  Units:
    name: units
    in: query
    description: Units type to return
    type: string
    enum:
      - imperial
      - metric
  Lang:
    name: lang
    in: query
    description: Language support
    type: string
    pattern: "[a-zA-Z]+(_[a-zA-Z]+)?"

paths:
  /weather:
    get:
      description: Get weather data
      operationId: getWeather
      parameters:
        - name: q
          in: query
          description: Query. Example city name
          type: string
        - name: id
          in: query
          description: Query by city Id
          type: string
        - name: lon
          in: query
          description: Query by longitude
          type: number
        - name: lat
          in: query
          description: Query by latitude
          type: number
        - name: zip
          in: query
          type: string
          description: Query by ZIP code. Format is `{zip code},{country code}`
          pattern: "[a-zA-Z0-9.]+(,[A-Za-z]+)?"
        - $ref: '#/parameters/Units'
        - $ref: '#/parameters/Lang'
        - $ref: '#/parameters/Appid'
      responses:
        default:
          description: Location weather, find details on https://openweathermap.org/current
          schema:
            type: object
            description: Location weather, find details on https://openweathermap.org/current

  /group:
    get:
      description: Get bulk weather data
      operationId: getBulkWeather
      parameters:
        - name: id
          in: query
          description: List of location ids
          type: array
          required: true
          maxItems: 20
          items:
            type: integer
            description: Location Id
          collectionFormat: csv
        - $ref: '#/parameters/Units'
        - $ref: '#/parameters/Lang'
        - $ref: '#/parameters/Appid'
      responses:
        default:
          description: Bulk request response
          schema:
            type: object
            description: Bulk request response
            properties:
              cnt:
                description: Number of location returned
                type: integer
              list:
                description: List of location weather
                type: array
                items:
                  description: Location weather, find details on https://openweathermap.org/current
                  type: object
